language: cpp

matrix:
  include:
    - dist: trusty
      compiler: gcc
      env: OCPN_TARGET=linux
      before_install:
        - sudo apt-get -qq update
        - >
          sudo apt-get --allow-unauthenticated install
          libwxgtk3.0-dev libwxgtk3.0-0 libgps-dev libglu1-mesa-dev
          libgtk2.0-dev libbz2-dev libtinyxml-dev libportaudio2 portaudio19-dev
          libcurl4-openssl-dev libexpat1-dev libcairo2-dev libarchive-dev
          liblzma-dev libexif-dev libsqlite3-dev libelf-dev gettext;
    - os:  osx
      compiler: clang
      env: OCPN_TARGET=osx
      before_install:
        - brew install cairo libexif xz libarchive
        - wget http://opencpn.navnux.org/build_deps/wx312_opencpn50_macos109.tar.xz
        - tar xJf wx312_opencpn50_macos109.tar.xz -C /tmp
        - export PATH="/usr/local/opt/gettext/bin:$PATH"
        - echo 'export PATH="/usr/local/opt/gettext/bin:$PATH"' >> ~/.bash_profile
    - dist: xenial
      env: OCPN_TARGET=mingw
      services:
        - docker
      before_install:
        - sudo apt-get -qq update
        - >
          echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"'
          | sudo tee /etc/default/docker > /dev/null
        - sudo service docker restart;
        - sleep 5;
        - sudo docker pull fedora:28;

before_install:
  - >
    echo -n | openssl s_client -connect https://scan.coverity.com:443 
    | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p'
    | sudo tee -a /etc/ssl/certs/ca
script:
  - ./travisci_build.sh
before_deploy:
  - >
    openssl aes-256-cbc -K $encrypted_831747f1d3db_key
    -iv $encrypted_831747f1d3db_iv  -in deploy_rsa.enc -out
    /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: >
     if [[ "$OCPN_TARGET" == "osx" ]]; then
     scp -oStrictHostKeyChecking=no
     -oUserKnownHostsFile=/dev/null $TRAVIS_BUILD_DIR/build/*.dmg
     travis@ocpnci.kalian.cz:files/;
     fi
  on:
    branch: master
    tags: false
notifications:
  email: false
git:
  depth: 10

env:
  - secure: "KC+tdCF5pSgrguqDcU3ZIzt6qxhu35aSGQYOJnsXFrC7XN7ACVCsb6kxjboAAoStvKuVy89OZLy6vdFpoZ+sHv0RtguV0RO70IX/A6m5PYAvnAXRSdCWoR4EfaV3UhN6hjTLGD2Wy6Hdkave9tt4IWeM8tAi/wvtbfE012ra4jU="

addons:
  coverity_scan:
    project:
      name: "OpenCPN/OpenCPN"
      description: "OpenCPN"
    notification_email: pavel@kalian.cz
    build_command_prepend: "mkdir -p build; cd build; cmake ..; make clean"
    build_command: "make"
    branch_pattern: coverity_scan
